name: Conventional Commits

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  pull-requests: write

jobs:
  conventional-commits:
    uses: laurigates/.github/.github/workflows/reusable-enforce-conventional-commits.yml@main
